# docker-compose.yml
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    image: bcp.api:0.0.0
    container_name: bcp-api
    ports:
      - "5163:5163"
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: "http://+:5163"
      ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT:-development}"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  ui:
    build:
      context: .
      dockerfile: ui.Dockerfile
    image: bcp.ui:0.0.0
    container_name: bcp-ui
    ports:
      - "5000:8080"
    depends_on:
      - api

volumes:
  dbdata: